
CREATE TABLE DEPT (
DEPT_Id NUMERIC not null, 
DEPT_Name VARCHAR(30),
constraint PK_dept primary key(dept_id)
);

CREATE TABLE EMPLOYEE (
EMPLOYEE_ID NUMERIC NOT NULL,FIRSTNAME VARCHAR(255),LASTNAME VARCHAR(255), DEPT_ID NUMERIC,
constraint PK_EMPLOYEE primary key(EMPLOYEE_ID),
constraint FK_EMPLOYEE_DEPT_ID foreign key(employee_id) references dept(dept_id));

CREATE SEQUENCE TEMPLOYEE_EMPLOYEE_ID_SEQ START WITH 1 INCREMENT BY 1 NO CYCLE 